export const ACTION_TYPES = {
  TOGGLE_PREVIEWS_MENU: 'TOGGLE_PREVIEWS_MENU',
  ADD_PREVIEW: 'ADD_PREVIEW',
  REMOVE_PREVIEW: 'REMOVE_PREVIEW',
  TOGGLE_ADD_ON_PREVIEW_MENU_VISIBILITY: 'GLE_ADD_ON_PREVIEW_MENU_VISIBILITY'
};